export const DEFAULT_ACTIVITY_CATEGORIES = [
  { name: "trivia", displayName: "Trivia Night", sortOrder: 1 },
  { name: "karaoke", displayName: "Karaoke", sortOrder: 2 },
  { name: "live-music", displayName: "Live Music", sortOrder: 3 },
  { name: "darts", displayName: "Darts Tournament", sortOrder: 4 },
  { name: "pool", displayName: "Billiards/Pool", sortOrder: 5 },
  { name: "poker", displayName: "Poker Night", sortOrder: 6 },
  { name: "dj", displayName: "DJ Night", sortOrder: 7 },
  { name: "open-mic", displayName: "Open Mic", sortOrder: 8 },
  { name: "comedy", displayName: "Comedy Night", sortOrder: 9 },
  { name: "watch-party", displayName: "Watch Party", sortOrder: 10 },
  { name: "happy-hour", displayName: "Happy Hour", sortOrder: 11 },
  { name: "food-special", displayName: "Food Special", sortOrder: 12 },
  { name: "drink-special", displayName: "Drink Special", sortOrder: 13 },
  { name: "themed-night", displayName: "Themed Night", sortOrder: 14 },
  { name: "paint-night", displayName: "Paint and Sip", sortOrder: 15 },
  { name: "bingo", displayName: "Bingo", sortOrder: 16 },
  { name: "other", displayName: "Other", sortOrder: 99 },
] as const;
