export const ACTIVITY_CATEGORIES = [
  { value: 'trivia', label: 'Trivia Night', icon: '🧠' },
  { value: 'karaoke', label: 'Karaoke', icon: '🎤' },
  { value: 'live-music', label: 'Live Music', icon: '🎸' },
  { value: 'darts', label: 'Darts Tournament', icon: '🎯' },
  { value: 'pool', label: 'Billiards/Pool', icon: '🎱' },
  { value: 'poker', label: 'Poker Night', icon: '🃏' },
  { value: 'dj', label: 'DJ Night', icon: '🎧' },
  { value: 'open-mic', label: 'Open Mic', icon: '🎙️' },
  { value: 'comedy', label: 'Comedy Night', icon: '😂' },
  { value: 'watch-party', label: 'Watch Party', icon: '📺' },
  { value: 'happy-hour', label: 'Happy Hour', icon: '🍺' },
  { value: 'food-special', label: 'Food Special', icon: '🍔' },
  { value: 'drink-special', label: 'Drink Special', icon: '🍹' },
  { value: 'themed-night', label: 'Themed Night', icon: '🎭' },
  { value: 'paint-night', label: 'Paint & Sip', icon: '🎨' },
  { value: 'bingo', label: 'Bingo', icon: '🎲' },
  { value: 'other', label: 'Other', icon: '⭐' },
];

export const DAYS_OF_WEEK = [
  { value: 0, label: 'Sunday', short: 'Sun' },
  { value: 1, label: 'Monday', short: 'Mon' },
  { value: 2, label: 'Tuesday', short: 'Tue' },
  { value: 3, label: 'Wednesday', short: 'Wed' },
  { value: 4, label: 'Thursday', short: 'Thu' },
  { value: 5, label: 'Friday', short: 'Fri' },
  { value: 6, label: 'Saturday', short: 'Sat' },
];

export const SUBSCRIPTION_PLANS = [
  {
    id: 'monthly',
    name: 'Monthly',
    price: 30,
    interval: 'month',
    description: 'Perfect for trying out BarPulse',
    features: [
      'Bar profile on the map',
      'Unlimited offerings & events',
      'Recurring weekly activities',
      'Special event flags',
      'Basic analytics',
      'Quick updates anytime',
    ],
  },
  {
    id: 'sixmonth',
    name: '6 Months',
    price: 150,
    interval: '6 months',
    description: 'Best value - save $30',
    originalPrice: 180,
    features: [
      'Everything in Monthly',
      'Save $30 vs monthly billing',
      'Priority support',
      'Extended analytics',
    ],
    popular: true,
  },
  {
    id: 'yearly',
    name: 'Annual',
    price: 250,
    interval: 'year',
    description: 'Maximum savings - save $110',
    originalPrice: 360,
    features: [
      'Everything in Monthly',
      'Save $110 vs monthly billing',
      'Priority support',
      'Extended analytics',
      'Early access to new features',
    ],
  },
];

export const US_STATES = [
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' },
  { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' },
];
