// @ts-expect-error - pdfkit types may not be fully compatible
import PDFDocument from 'pdfkit';
import { format } from 'date-fns';

interface ReportHeader {
  barName: string;
  address: string;
  city: string;
  state: string;
  dateRange: { start: Date; end: Date };
  preparedBy: string;
  preparedByEmail: string;
}

interface ExecutiveSummary {
  startInventoryValue: number;
  endInventoryValue: number;
  totalUsage: number;
  totalPurchases: number;
  totalVariance: number;
  pourCostPct: number | null;
  topCostItems: Array<{ name: string; value: number }>;
  topUsageItems: Array<{ name: string; usage: number }>;
}

interface InventoryDetailRow {
  category: string;
  name: string;
  sizeMl: number;
  costPerBottle: number;
  costPerMl: number;
  startQty: number;
  receivedQty: number;
  usedQty: number;
  endingQty: number;
  physicalQty: number | null;
  varianceQty: number | null;
  varianceValue: number | null;
  currentValue: number;
}

interface UsageSummaryRow {
  date: string;
  bottlesUsed: number;
  mlUsed: number;
  costUsed: number;
}

interface Exception {
  type: 'low_stock' | 'high_variance' | 'high_usage' | 'missing_data';
  itemName: string;
  details: string;
  value?: number;
}

export interface InventoryReportData {
  header: ReportHeader;
  summary: ExecutiveSummary;
  details: InventoryDetailRow[];
  usageSummary: UsageSummaryRow[];
  exceptions: Exception[];
}

export function generateInventoryPDF(data: InventoryReportData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'LETTER', margin: 50 });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      let currentPage = 1;
      const totalPages = estimatePageCount(data);

      // Helper functions
      const addPageNumber = () => {
        doc.fontSize(8)
          .fillColor('#666666')
          .text(
            `Page ${currentPage} of ~${totalPages} | Generated by BarLink`,
            50,
            doc.page.height - 30,
            { align: 'center' }
          );
        currentPage++;
      };

      const checkPageBreak = (spaceNeeded: number) => {
        if (doc.y + spaceNeeded > doc.page.height - 80) {
          addPageNumber();
          doc.addPage();
        }
      };

      // HEADER
      doc.fontSize(20).fillColor('#000000').text('BarLink Inventory Report', { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(12).fillColor('#333333').text(data.header.barName, { align: 'center' });
      doc.fontSize(10).fillColor('#666666')
        .text(`${data.header.address}, ${data.header.city}, ${data.header.state}`, { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(9).fillColor('#888888')
        .text(
          `Report Period: ${format(data.header.dateRange.start, 'MMM dd, yyyy')} - ${format(data.header.dateRange.end, 'MMM dd, yyyy')}`,
          { align: 'center' }
        );
      doc.text(`Generated: ${format(new Date(), 'MMM dd, yyyy h:mm a')}`, { align: 'center' });
      doc.text(`Prepared by: ${data.header.preparedBy} (${data.header.preparedByEmail})`, { align: 'center' });
      doc.moveDown(1.5);

      // EXECUTIVE SUMMARY
      doc.fontSize(14).fillColor('#000000').text('Executive Summary', { underline: true });
      doc.moveDown(0.5);

      const summaryData = [
        ['Inventory Value (Start):', `$${data.summary.startInventoryValue.toFixed(2)}`],
        ['Inventory Value (End):', `$${data.summary.endInventoryValue.toFixed(2)}`],
        ['Total Usage (Period):', `$${data.summary.totalUsage.toFixed(2)}`],
        ['Total Purchases:', data.summary.totalPurchases > 0 ? `$${data.summary.totalPurchases.toFixed(2)}` : 'N/A'],
        ['Total Variance:', `$${data.summary.totalVariance.toFixed(2)}`],
        ['Pour Cost %:', data.summary.pourCostPct ? `${data.summary.pourCostPct.toFixed(1)}%` : 'N/A'],
      ];

      doc.fontSize(10).fillColor('#333333');
      summaryData.forEach(([label, value]) => {
        doc.text(label, 70, doc.y, { continued: true, width: 200 });
        doc.fillColor('#000000').text(value, { align: 'right' });
        doc.fillColor('#333333');
        doc.moveDown(0.3);
      });

      doc.moveDown(0.5);

      // Top 5 Highest Cost Items
      doc.fontSize(11).fillColor('#000000').text('Top 5 Highest-Cost Items:', { underline: true });
      doc.moveDown(0.3);
      doc.fontSize(9).fillColor('#333333');
      data.summary.topCostItems.slice(0, 5).forEach((item, idx) => {
        doc.text(`${idx + 1}. ${item.name}: $${item.value.toFixed(2)}`);
        doc.moveDown(0.2);
      });

      doc.moveDown(0.5);

      // Top 5 Fastest Moving Items
      doc.fontSize(11).fillColor('#000000').text('Top 5 Fastest-Moving Items:', { underline: true });
      doc.moveDown(0.3);
      doc.fontSize(9).fillColor('#333333');
      data.summary.topUsageItems.slice(0, 5).forEach((item, idx) => {
        doc.text(`${idx + 1}. ${item.name}: ${item.usage.toFixed(2)} units`);
        doc.moveDown(0.2);
      });

      doc.moveDown(1);

      checkPageBreak(200);

      // INVENTORY DETAIL TABLE
      doc.fontSize(14).fillColor('#000000').text('Inventory Detail', { underline: true });
      doc.moveDown(0.5);

      const colWidths = [120, 60, 50, 50, 50, 60];
      const colX = [50, 170, 230, 280, 330, 380];
      const headers = ['Item', 'Category', 'Size(ml)', 'Cost/Unit', 'Ending Qty', 'Value'];

      const drawTableHeader = (y: number) => {
        doc.fontSize(8).fillColor('#FFFFFF');
        doc.rect(50, y, 500, 20).fillAndStroke('#4A5568', '#4A5568');
        headers.forEach((header, idx) => {
          doc.text(header, colX[idx] + 3, y + 5, { width: colWidths[idx] - 6 });
        });
        doc.fillColor('#333333');
      };

      drawTableHeader(doc.y);
      doc.moveDown(1.5);

      data.details.forEach((row, rowIdx) => {
        checkPageBreak(25);
        
        if (doc.y < 100 && rowIdx > 0) {
          drawTableHeader(doc.y);
          doc.moveDown(1.5);
        }

        const rowY = doc.y;
        const rowHeight = 20;

        // Alternate row background
        if (rowIdx % 2 === 0) {
          doc.rect(50, rowY, 500, rowHeight).fill('#F7FAFC');
        }

        doc.fontSize(8).fillColor('#000000');
        doc.text(row.name, colX[0] + 2, rowY + 5, { width: colWidths[0] - 4, ellipsis: true });
        doc.text(row.category, colX[1] + 2, rowY + 5, { width: colWidths[1] - 4 });
        doc.text(row.sizeMl.toString(), colX[2] + 2, rowY + 5, { width: colWidths[2] - 4 });
        doc.text(`$${row.costPerBottle.toFixed(2)}`, colX[3] + 2, rowY + 5, { width: colWidths[3] - 4 });
        doc.text(row.endingQty.toFixed(2), colX[4] + 2, rowY + 5, { width: colWidths[4] - 4 });
        doc.text(`$${row.currentValue.toFixed(2)}`, colX[5] + 2, rowY + 5, { width: colWidths[5] - 4 });

        doc.y = rowY + rowHeight;
      });

      doc.moveDown(1);

      checkPageBreak(150);

      // USAGE BY DAY
      if (data.usageSummary.length > 0) {
        doc.fontSize(14).fillColor('#000000').text('Usage Summary by Day', { underline: true });
        doc.moveDown(0.5);

        doc.fontSize(9).fillColor('#333333');
        data.usageSummary.forEach((usage) => {
          doc.text(
            `${usage.date}: ${usage.bottlesUsed.toFixed(1)} bottles, ${usage.mlUsed.toFixed(0)}ml, $${usage.costUsed.toFixed(2)}`
          );
          doc.moveDown(0.2);
        });

        doc.moveDown(1);
      }

      checkPageBreak(200);

      // EXCEPTIONS & ALERTS
      if (data.exceptions.length > 0) {
        doc.fontSize(14).fillColor('#000000').text('Exceptions & Alerts', { underline: true });
        doc.moveDown(0.5);

        const groupedExceptions = {
          low_stock: data.exceptions.filter((e) => e.type === 'low_stock'),
          high_variance: data.exceptions.filter((e) => e.type === 'high_variance'),
          high_usage: data.exceptions.filter((e) => e.type === 'high_usage'),
          missing_data: data.exceptions.filter((e) => e.type === 'missing_data'),
        };

        Object.entries(groupedExceptions).forEach(([type, items]) => {
          if (items.length > 0) {
            const title = type.replace(/_/g, ' ').replace(/\b\w/g, (l) => l.toUpperCase());
            doc.fontSize(11).fillColor('#DC2626').text(`⚠ ${title} (${items.length})`, { underline: true });
            doc.moveDown(0.3);
            doc.fontSize(9).fillColor('#333333');

            items.slice(0, 10).forEach((item) => {
              doc.text(`• ${item.itemName}: ${item.details}`, { indent: 10 });
              doc.moveDown(0.2);
            });

            doc.moveDown(0.5);
          }
        });
      }

      // FOOTER
      addPageNumber();

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

function estimatePageCount(data: InventoryReportData): number {
  const headerPages = 1;
  const detailRows = data.details.length;
  const rowsPerPage = 25;
  const detailPages = Math.ceil(detailRows / rowsPerPage);
  const usagePages = Math.ceil(data.usageSummary.length / 40);
  const exceptionPages = Math.ceil(data.exceptions.length / 30);
  return headerPages + detailPages + usagePages + exceptionPages;
}
