-- Add entitlement and billing columns with safe defaults
ALTER TABLE "Bar"
ADD COLUMN IF NOT EXISTS "basePlan" TEXT NOT NULL DEFAULT 'BASIC',
ADD COLUMN IF NOT EXISTS "addonPro" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "addonPremium" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "addonInventory" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "planInterval" TEXT NOT NULL DEFAULT 'MONTHLY',
ADD COLUMN IF NOT EXISTS "boostCreditsBalance" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "lastCalculatedTaxRate" DECIMAL(5,4) DEFAULT 0.0825;
